language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - 2.1.5
 - 2.2.0
 - ruby-head
 - jruby
 - ree

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: jruby
    - rvm: ree

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y poppler-utils poppler-data
